# Generated by Django 4.2.2 on 2023-06-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/Screenshot_2022-06-23_103042_2_p9rxvr.png', upload_to='profile_pics'),
        ),
    ]
